//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kielb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KB_Bodegas
    {
        public short Suc_Id { get; set; }
        public short Bodega_Id { get; set; }
        public System.DateTime Mov_Fecha { get; set; }
        public System.DateTime Mov_Fecha_Aplicado { get; set; }
        public string Mov_Estado { get; set; }
        public string Mov_Comentario { get; set; }
        public int Mov_Id { get; set; }
        public int Mov_Numero { get; set; }
    }
}
