//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kielb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KB_CuadroFaltINV
    {
        public int id { get; set; }
        public Nullable<int> suc_id { get; set; }
        public Nullable<int> bodega_id { get; set; }
        public Nullable<System.DateTime> fecha_apertura { get; set; }
        public Nullable<System.DateTime> fecha_aplicacion { get; set; }
        public string estado { get; set; }
        public string comentario { get; set; }
        public Nullable<int> id_mov { get; set; }
        public Nullable<int> Num_Mov { get; set; }
        public Nullable<int> aplica { get; set; }
        public Nullable<int> tipo_cobro { get; set; }
        public Nullable<int> tipo_faltante { get; set; }
        public Nullable<decimal> costo_total { get; set; }
    }
}
