//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kielb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KB_Calculo_Bono
    {
        public int id { get; set; }
        public Nullable<decimal> comision { get; set; }
        public Nullable<decimal> cuadroA { get; set; }
        public Nullable<decimal> cuadroB { get; set; }
        public Nullable<decimal> cuadroC { get; set; }
        public Nullable<decimal> consumo { get; set; }
        public Nullable<decimal> canje { get; set; }
        public Nullable<decimal> checklist { get; set; }
        public Nullable<decimal> faltInv { get; set; }
        public Nullable<decimal> FaltCaja { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string empleado_id { get; set; }
        public string puesto { get; set; }
        public Nullable<int> suc_id { get; set; }
        public string nombre { get; set; }
    }
}
