//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kielb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KB_CalculoBono
    {
        public int id { get; set; }
        public Nullable<int> suc_id { get; set; }
        public Nullable<int> puesto { get; set; }
        public Nullable<int> vendedor_id { get; set; }
        public Nullable<decimal> monto_bono { get; set; }
        public Nullable<decimal> falt_inv { get; set; }
        public Nullable<decimal> falt_caja { get; set; }
        public Nullable<decimal> total_deduciones { get; set; }
        public Nullable<decimal> total_bono { get; set; }
        public Nullable<decimal> diferencia_N { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
