//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kielb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KB_ConsultaNotas
    {
        public int Vendedor_Id { get; set; }
        public string vendedor_nombre_completo { get; set; }
        public string cliente { get; set; }
        public System.DateTime Fecha { get; set; }
        public double Monto { get; set; }
        public string Nombre_Corto { get; set; }
        public string Num_Nota { get; set; }
        public string CtaContable { get; set; }
        public int CentroCosto { get; set; }
    }
}
