//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kielb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KB_DatosUsuario
    {
        public int Id { get; set; }
        public int Empleado_id { get; set; }
        public string Nombre { get; set; }
        public string email { get; set; }
        public string pass { get; set; }
        public string Emp_Nombre { get; set; }
        public string Suc_Nombre { get; set; }
        public string Estado { get; set; }
        public string Rol { get; set; }
    }
}
