//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kielb.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class KB_Porcentajes
    {
        public int id { get; set; }
        //Ruta para obtener la ruta del archivo en excel
        public HttpPostedFileBase ruta { get; set; }
        public Nullable<decimal> cumplimiento { get; set; }
        public Nullable<decimal> comision { get; set; }
        public Nullable<decimal> cuadroA { get; set; }
        public Nullable<decimal> cuadroB { get; set; }
        public Nullable<decimal> cuadroC { get; set; }
        public Nullable<decimal> consumo { get; set; }
        public Nullable<decimal> checklist { get; set; }
        public Nullable<int> mes { get; set; }
        public Nullable<int> año { get; set; }
        public Nullable<decimal> canje { get; set; }
        public Nullable<int> suc_id { get; set; }
    }
}
