//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kielb.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class KB_Presupuesto_Far
    {
        public int Id { get; set; }
        //Ruta para obtener la ruta del archivo en excel
        public HttpPostedFileBase ruta { get; set; }
        public Nullable<int> Suc_id { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<int> Año { get; set; }
        public Nullable<decimal> checklist { get; set; }

        public Nullable<int> supervisor_id { get; set; }
    }
}
