//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kielb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KB_UsuariosKielsaBonos
    {
        public int Id { get; set; }
        public int Empleado_id { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Sucursal_id { get; set; }
        public string pass { get; set; }
        public Nullable<int> ID_Estado { get; set; }
        public Nullable<int> ID_Rol { get; set; }
        public string email { get; set; }
        public string token_recovery { get; set; }
        public Nullable<int> Emp_id { get; set; }
    }
}
