//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kielb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SITEPLUSEntities : DbContext
    {
        public SITEPLUSEntities()
            : base("name=SITEPLUSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KB_Porcentajes> KB_Porcentajes { get; set; }
        public virtual DbSet<KB_Presupuesto_Dom> KB_Presupuesto_Dom { get; set; }
        public virtual DbSet<KB_Presupuesto_Far> KB_Presupuesto_Far { get; set; }
        public virtual DbSet<KB_Mantenimiento_Perfiles_Y_Roles> KB_Mantenimiento_Perfiles_Y_Roles { get; set; }
        public virtual DbSet<KB_UsuariosKielsaBonos> KB_UsuariosKielsaBonos { get; set; }
        public virtual DbSet<TBL_Estado_Uuarios> TBL_Estado_Uuarios { get; set; }
        public virtual DbSet<VSP_Empresas> VSP_Empresas { get; set; }
        public virtual DbSet<VSP_TR_SUCURSAL> VSP_TR_SUCURSAL { get; set; }
        public virtual DbSet<TBL_Anios> TBL_Anios { get; set; }
        public virtual DbSet<TBL_MESES> TBL_MESES { get; set; }
        public virtual DbSet<VSP_KB_Vendedores_x_pais> VSP_KB_Vendedores_x_pais { get; set; }
        public virtual DbSet<KB_CalculoBono> KB_CalculoBono { get; set; }
        public virtual DbSet<KB_CobroVendedor> KB_CobroVendedor { get; set; }
        public virtual DbSet<KB_CuadroFaltINV> KB_CuadroFaltINV { get; set; }
        public virtual DbSet<VSP_KB_DatosUsuarios> VSP_KB_DatosUsuarios { get; set; }
        public virtual DbSet<VSP_KB_NombreFaltantes> VSP_KB_NombreFaltantes { get; set; }
        public virtual DbSet<KB_Calculo_Bono> KB_Calculo_Bono { get; set; }
        public virtual DbSet<KB_CalculoFaltCaja> KB_CalculoFaltCaja { get; set; }
        public virtual DbSet<KB_Empleados> KB_Empleados { get; set; }
        public virtual DbSet<KB_TipoEmpleados> KB_TipoEmpleados { get; set; }
        public virtual DbSet<KB_ConsultaNotas> KB_ConsultaNotas { get; set; }
        public virtual DbSet<KB_Consumo> KB_Consumo { get; set; }
        public virtual DbSet<KB_CuadroBasicoA> KB_CuadroBasicoA { get; set; }
        public virtual DbSet<KB_CuadroBasicoB> KB_CuadroBasicoB { get; set; }
        public virtual DbSet<KB_CuadroBasicoC> KB_CuadroBasicoC { get; set; }
        public virtual DbSet<KB_DatosUsuario> KB_DatosUsuario { get; set; }
        public virtual DbSet<KB_Venta_total> KB_Venta_total { get; set; }
        public virtual DbSet<KB_VentaNeta> KB_VentaNeta { get; set; }
        public virtual DbSet<VSP_KB_perfilesKB> VSP_KB_perfilesKB { get; set; }
        public virtual DbSet<VSP_KB_TipoFaltantes_X_Pais> VSP_KB_TipoFaltantes_X_Pais { get; set; }

        public System.Data.Entity.DbSet<kielb.Models.VentaTotales> VentaTotales { get; set; }
    }
}
