//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kielb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSP_KB_Vendedores_x_pais
    {
        public short Emp_Id { get; set; }
        public short Cadena_Id { get; set; }
        public int Vendedor_Id { get; set; }
        public string Vendedor_Nombre { get; set; }
        public string Vendedor_Apellido1 { get; set; }
        public string Vendedor_Apellido2 { get; set; }
        public string Vendedor_Nombre_Completo { get; set; }
        public System.DateTime Vendedor_Fec_Actualizacion { get; set; }
        public bool Vendedor_Activo { get; set; }
        public string Codigo_Interfaz { get; set; }
        public short Suc_Id { get; set; }
    }
}
