//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kielb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSP_KB_TipoFaltantes_X_Pais
    {
        public short Emp_Id { get; set; }
        public short Suc_Id { get; set; }
        public short Bodega_Id { get; set; }
        public int Mov_Id { get; set; }
        public short Tipo_Id { get; set; }
        public short Usuario_Id { get; set; }
        public short Suc_Destino { get; set; }
        public short Bodega_Destino { get; set; }
        public short Mov_Tipo_Ajuste { get; set; }
        public System.DateTime Mov_Fecha { get; set; }
        public System.DateTime Mov_Fecha_Aplicado { get; set; }
        public System.DateTime Mov_Fecha_Anulado { get; set; }
        public System.DateTime Mov_Fecha_Despachado { get; set; }
        public System.DateTime Mov_Fecha_Impreso { get; set; }
        public System.DateTime Mov_Fecha_Ingreso { get; set; }
        public System.DateTime Mov_Fecha_Recibido { get; set; }
        public decimal Mov_Subtotal { get; set; }
        public decimal Mov_Total { get; set; }
        public decimal Mov_Precio_Total { get; set; }
        public string Mov_Comentario { get; set; }
        public string Mov_Estado { get; set; }
        public bool Mov_Utilizado { get; set; }
        public bool Mov_Interbodega { get; set; }
        public bool Mov_Aplicar_Consignacion { get; set; }
        public short Mov_Usuario_Aplica { get; set; }
        public short Mov_Usuario_Anula { get; set; }
        public short Mov_Usuario_Recibe { get; set; }
        public decimal Mov_Subtotal_Dolar { get; set; }
        public decimal Mov_Subtotal_Ant_Dolar { get; set; }
        public int Asiento_id { get; set; }
        public int Orden_Id { get; set; }
        public int Asiento_Recibido_Id { get; set; }
        public string Mov_Origen { get; set; }
        public int Mov_Numero { get; set; }
        public string Serie_id { get; set; }
        public string Resolucion_id { get; set; }
        public System.DateTime Resolucion_Fecha { get; set; }
        public int Resolucion_Doc_Inicio { get; set; }
        public int Resolucion_Doc_Final { get; set; }
        public string Resolucion_Tipo_Comprobante_FE { get; set; }
        public System.DateTime Resolucion_Fec_Vencimiento { get; set; }
        public short Resolucion_Establecimiento { get; set; }
        public short Resolucion_Punto_Emision { get; set; }
    }
}
