//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kielb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSP_KB_NombreFaltantes
    {
        public short Emp_Id { get; set; }
        public short Tipo_Id { get; set; }
        public string Tipo_Nombre { get; set; }
        public bool Tipo_Estadistica { get; set; }
        public short Tipo_Tipo_Movimiento { get; set; }
        public bool Tipo_InterBodega { get; set; }
        public bool Tipo_Suma_Inventario { get; set; }
        public System.DateTime Tipo_Fec_Actualizacion { get; set; }
        public bool Tipo_Mov_Merma { get; set; }
    }
}
